language: python

sudo: required
dist: trusty

matrix:
  include:
    - env: TOX_ENV=py35
      python: 3.5
    - env: TOX_ENV=py36
      python: 3.6

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - sudo apt-get install -y libffi-dev libssl-dev shellcheck pandoc
  - nvm install 8.1.1
  - nvm use 8.1.1

install:
  - curl -sSL -o /usr/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.2.6/hadolint-Linux-x86_64 && chmod a+x /usr/bin/hadolint
  - npm install -g eslint csslint sass-lint jsonlint stylelint eslint-plugin-react eslint-plugin-react-native babel-eslint
  - pip install -U tox

script: tox -e $TOX_ENV

after_success:
  - pip install codecov
  - codecov
  - |
    if [[ "${TRAVIS_TAG:-}" != "" && "$TOX_ENV" == "py36" ]]; then
      pandoc --from markdown --to rst --output=README.rst README.md;
      python3.6 setup.py sdist bdist_wheel;
      python3.6 -m pip install twine;
      python3.6 -m twine upload --skip-existing dist/*;
    fi
